config/routes.rb
Rails.application.routes.draw do
  get 'todo_lists/:todo_list_id/tags/:tag', to: 'todo_lists#show', as: :tag
  get 'todo_lists/:todo_list_id/typeahead/:query' => 'todo_items#typeahead'
  resources :todo_lists do
  	resources :todo_items do
        member do
          patch :complete,:incomplete,:efficiency
        end
    end
  end
  resources :indicators do
    collection { post :sort }
  end 
  resources :documentations
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :kpis
  devise_for :users
  root "indicators#index"

end

app/models/documentation.rb
class Documentation < ActiveRecord::Base
	has_attached_file :file
	belongs_to :category
	belongs_to :department
	validates_attachment :file, :content_type => {:content_type => %w(image/jpeg image/jpg image/png application/pdf application/msword application/vnd.ms-excel application/vnd.openxmlformats-officedocument.spreadsheetml.sheet application/vnd.openxmlformats-officedocument.wordprocessingml.document application/vnd.openxmlformats-officedocument.presentationml.presentation application/vnd.openxmlformats-officedocument.spreadsheetml.sheet)}
end

app/controllers/documentations_controller.rb
class DocumentationsController < ApplicationController
  before_action :set_documentation, only: [:show, :edit, :update, :destroy]
  before_filter :must_be_admin, only: [:new,:create,:edit,:update,:destroy]
  # GET /documentations
  # GET /documentations.json
  def index

    if params[:department].blank?
     @documentations = Documentation.all.order('created_at DESC')
    else
      @department_id=Department.find_by(name: params[:department]).id
      @documentations = Documentation.where(department_id: @department_id).order('created_at DESC')
    end

    respond_to do |format|
      format.html
      format.json { render json: @documentations }
    end
  end

  # GET /documentations/1
  # GET /documentations/1.json
  def show
    @documentation = Documentation.find(params[:id])
  end

  # GET /documentations/new
  def new
    @documentation = Documentation.new
  end

  # GET /documentations/1/edit
  def edit
    @documentations = Documentation.find(params[:id])
    respond_to do |format|
        format.html  #If it's a html request this line tell rails to look for new_release.html.erb in your views directory
        format.js #If it's a js request this line tell rails to look for new_release.js.erb in your views directory
      end
    
  end

  # POST /documentations
  # POST /documentations.json
  def create
    @documentation = Documentation.new(documentation_params)

    respond_to do |format|
      if @documentation.save
        format.html { redirect_to documentations_path }
        format.json { render :show, status: :created, location: @documentation }
      else
        format.html { render :new }
        format.json { render json: @documentation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /documentations/1
  # PATCH/PUT /documentations/1.json
  def update
    @documentations = Documentation.find(params[:id])

    if @documentations.update(params[:documentation].permit(:format, :title, :version, :file, :process, :doc, :category_id, :department_id))
      redirect_to documentations_path
    else
      render 'edit'
    end
  end

  # DELETE /documentations/1
  # DELETE /documentations/1.json
  def destroy
    @documentation.destroy
    respond_to do |format|
      format.html { redirect_to documentations_url, notice: 'Documentation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def must_be_admin
      unless current_user && current_user.admin?
        redirect_to root_path, notice: "must be admin"
      end
    end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_documentation
      @documentation = Documentation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def documentation_params
      params.require(:documentation).permit(:format, :title, :version, :file, :process, :doc, :category_id, :department_id)
    end
end

app/helpers/documentations_helper.rb
module DocumentationsHelper



end

app/views/documentations/_form.html.erb
        <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title" id="myModalLabel"> Documentation</h4>
                </div>
                <div class="modal-body">
                    <%= form_for @documentation, html: { multipart: true }  do |f| %>
                    <% if @documentation.errors.any? %>
               <div id="error_explanation">
                <h2><%= pluralize(@documentation.errors.count, "error") %> prohibited this documentation from being saved:</h2>

                <ul>
                <% @documentation.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
                </ul>
              </div>
              <% end %>
             <p>
                <%= f.label :departement %>
                <%= f.collection_select :department_id, Category.all, :id, :name, {prompt: "Choose a department"}, { :class => 'form-control' } %>
              </p>
               <p>
                  <%= f.label :doc %><br>
                  <%= f.select(:doc, ['Processus','Procédure','Instruction'], {}, { :class => 'form-control' }) %>
              </p>
              <p>
                  <%= f.label :format %><br>
                  <%= f.text_field :format,:placeholder => "Entrer un format", :class=>"form-control" %>
              </p>
              <p>
                <%= f.label :title %><br>
                <%= f.text_field :title,:placeholder => "Entrer un titre", :class=>"form-control" %>
              </p>
              <p>
                <%= f.label :version %><br>
                <%= f.number_field :version, :class=>"form-control" %>
              </p>
              <p>
                <%= f.label :file %><br>
                <%= f.file_field :file %>
              </p>
                      <div class="modal-footer">
                          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                         <%= f.submit :class=>"btn btn-primary"  %>
                      </div>
          <% end %>
        </div>

app/views/documentations/edit.html.erb
<h1>Editing Documentation</h1>

<%= render 'form' %>

<%= link_to 'Show', @documentation %> |
<%= link_to 'Back', documentations_path %>

app/views/documentations/edit.js.erb
$("#modal-edit").find(".modal-content").html("<%= j (render 'documentations/form') %>");
$("#modal-edit").modal('show');

app/views/documentations/index.html.erb
  <section class="main-content-wrapper">
            <section id="main-content">
                 <div class="row">
                    <div class="col-md-12">
                      <span style="color: #9eafba;text-decoration: none;font-size: 1.5em;"><i class="fa fa-tag fa-1x"> Filter :</i></span>
                      <%= link_to "All", documentations_path, :class => "btn btn-primary" %>
                      <% Department.all.each do |department| %>
                        <%= link_to department.name, documentations_path(department: department.name), :class => "btn btn-primary" %>
                      <% end %>
                      <br>  <br>
                    </div>
                   </div>

                <div class="row">
                    <div class="col-md-12">
                        <div class="panel panel-default">
                            <div class="panel-heading">
                                <h3 class="panel-title">Documentation</h3>
                                <div class="actions pull-right">
                                    <% if current_user.admin? %>
                                      <%= link_to "New documentation", new_documentation_path, {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#modal-new', :class => "btn btn-primary btn-xs"}%> 
                                    <% end %>
                                </div>
                            </div>
                            <div class="panel-body">

                              <p id="notice"><%= notice %></p>
                             
                              <table id="documentations" class="table table-striped table-bordered" cellspacing="0" width="100%">
                                <thead>
                                  <tr>
                                    <th>Processus</th>
                                    <th>Type</th>
                                    <th>Title</th>
                                    <th>Format</th>
                                    <th>Version</th>
                                    <th>Show</th>
                                    <% if current_user.admin? %>
                                      <th>Edit</th>
                                      <th>Delete</th>
                                    <% end %>
                                  </tr>
                                </thead>

                                <tbody>
                                    <% @documentations.each do |documentation| %>
                                    <tr>
                                      <td><%= documentation.department.name %></td>
                                      <td><%= documentation.doc %></td>
                                      <td><%= documentation.title %></td>
                                      <td><%= File.extname(documentation.file.url).strip.downcase[1..-1].partition("?").first%></td>
                                      <td>Version <%= documentation.version %></td>
                                      <td width="4%"> <%= link_to documentation.file.url, target: "_blank", :class => "btn btn-primary" do %><i class="fa fa-search"> Show</i><% end %></td></td>
                                       <% if current_user.admin? %>
                                            <td width="4%"><%= link_to edit_documentation_path(documentation), {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#modal-edit', :class => "btn btn-default"}  do %><i class="fa fa-edit"></i> Edit <% end %></td>
                                            <td width="4%"><%= link_to documentation_path(documentation),data: {:confirm => 'Are you sure?'}, :method => :delete, :class => "btn btn-danger", :style=>'color:#FFFFFF;' do %><i class="fa fa-trash-o"> Delete</i><% end %></td>
                                        <% end %>
                                    </tr> 

                                    <% end %>
                                </tbody>
                              </table>

                              <br>

          </div>
        </div>
      </div>
    </div>

  </section>
</section>


  <script type="text/javascript">
    $(document).ready(function() {
        $('#documentations').DataTable({
    "pageLength": 50,
    "bLengthChange": false,
    "bFilter": true,
    "bInfo": false,
    "bAutoWidth": false });
    } );
  </script>
  
  <!--main content end-->
         <!-- Basic Modal -->
    <div id="modal-new" class="modal fade" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">

        </div>
      </div>
  </div>
  
  <div id="modal-edit" class="modal fade" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">

        </div>
      </div>
  </div>
    <!-- End Basic Modal -->
    <!-- Form Modal -->

      <!-- End Form Modal -->

app/views/documentations/new.html.erb
<section class="main-content-wrapper">
            <section id="main-content">
                <div class="row">

<h1>New Documentation</h1>

<%= render 'form' %>

<%= link_to 'Back', documentations_path %>
    </div>

  </section>
</section>

app/views/documentations/new.js.erb
$("#modal-new").find(".modal-content").html("<%= j (render 'documentations/form') %>");
$("#modal-new").modal('show');

app/views/documentations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Format:</strong>
  <%= @documentation.format %>
</p>

<p>
  <strong>Title:</strong>
  <%= @documentation.title %>
</p>

<p>
  <strong>Version:</strong>
  <%= @documentation.version %>
</p>

p>
  <strong>Version:</strong>
  <%= @documentation.file %>
</p>

<%= link_to 'Edit', edit_documentation_path(@documentation) %> |
<%= link_to 'Back', documentations_path %>