config/routes.rb
Rails.application.routes.draw do
  get 'todo_lists/:todo_list_id/tags/:tag', to: 'todo_lists#show', as: :tag
  get 'todo_lists/:todo_list_id/typeahead/:query' => 'todo_items#typeahead'
  resources :todo_lists do
  	resources :todo_items do
        member do
          patch :complete,:incomplete,:efficiency
        end
    end
  end
  resources :indicators do
    collection { post :sort }
  end 
  resources :documentations
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :kpis
  devise_for :users
  root "indicators#index"

end

app/models/indicator.rb
class Indicator < ActiveRecord::Base
	self.inheritance_column = :foo
	belongs_to :category
	belongs_to :department
	belongs_to :user
	validates :department, presence: true
	validates :name, presence: true
	validates :data, presence: true
	acts_as_list
	acts_as_taggable
	acts_as_taggable_on :tag_list


end

app/controllers/indicators_controller.rb
class IndicatorsController < ApplicationController
	before_filter :must_be_admin, only: [:new,:create,:edit,:update,:destroy]
	before_filter :authenticate_user!, only: [:index,:show]
	def index
		@indicators = Indicator.where('user_id = ? or public = ?', current_user, true).order(:position)
		if  params[:tag].blank? && params[:department].blank? 
			@indicators = Indicator.where('user_id = ? or public = ?', current_user, true).order(:position)
		elsif params[:tag] && params[:department].blank?
    		@indicators = Indicator.tagged_with(params[:tag]).where('user_id = ? or public = ?', current_user, true).order(:position)
    	else params[:department] && params[:tag].blank?
     		@department_id=Department.find_by(name: params[:department]).id
			@indicators = Indicator.where('user_id = ? and department_id = ? or public = ? and department_id = ? ', current_user, @department_id, true, @department_id).order(:position)
   		end

		@kpis = Kpi.all
		@charts=[]
		@indicators.each do |indicator|
			
			@chart = LazyHighCharts::HighChart.new('graph') do |f|
					  
					  	serie = (indicator.data.split("\n"))
					  	x = serie.first.split(',').map(&:to_s)
					  
					  	serie.drop(1).each do |serie|
					  		tampon = serie.split('|').first
					  		data= tampon.split(',').map(&:to_f).drop(1)
					  		name= serie.split(',').map(&:to_s).first


					  		options = serie.split('|').last
					  		option = options.split(',').map(&:to_s)
					  	
						  		graph = indicator.graph.split('_').map(&:to_s).last
						  			
						  			if (name.upcase=='OBJECTIF' || name.upcase=='BUDGET')
						  				puts f.series(type: 'line', name: name , yAxis: 0, data: data, color: '#ff5050')
						  			else

							  			if option.any? { |e| e.include? 'type'}
							  				puts f.series(name: name, yAxis: 0, data: data, type: option.find{ |str| str.include?('type')}.split(':').map(&:to_s).last) 
							  			else

								  			if option.any? { |e| e.include? 'stack'}
								  				puts f.series(name: name, yAxis: 0, data: data, stack: option.find{ |str| str.include?('stack')}.split(':').map(&:to_s).last) 
								  			else

									  			if option.any? { |e| e.include? 'stack'} && option.any? { |e| e.include? 'type'}
									  				puts f.series(name: name, yAxis: 0, data: data, stack: option.find{ |str| str.include?('stack')}.split(':').map(&:to_s).last, type: option.find{ |str| str.include?('type')}.split(':').map(&:to_s).last) 
									  			else
						  							if indicator.graph == "spider_line"
									  					puts f.series(name: name, data: data, pointPlacement: 'on', dataLabels: {enabled: false})
									  					puts f.yAxis [{gridLineInterpolation: 'polygon', lineWidth: 0, min: 0}]
						  								puts f.xAxis [categories: x, tickmarkPlacement: 'on', lineWidth: 0]
						  								puts f.pane [size: '80%']
						  							
						  							
									  				else
						  								puts f.series(name: name , yAxis: 0, data: data)
						  							end
						  						end
						  					end
						  				end
						  			end
						  					
						  				
						  				
						  				

					  		
					  	end

					  	if (indicator.graph == "stacked_bar") || (indicator.graph =="stacked_column") || (indicator.graph =="stacked_area")
					  		f.plotOptions(series: {stacking: 'normal',dataLabels: {enabled: 'true',color: '#FFFFFF'}})
					  		f.yAxis [{title: {text: indicator.yaxis, margin: 70},stackLabels:{enabled: 'true', style:{fontWeight:'bold', color: 'gray'}}}]
					  	else 
					  		f.plotOptions(series: {dataLabels: {enabled: 'true'}})
					  		f.yAxis [{title: {text: indicator.yaxis, margin: 70} },]
					  	end
					  	
					  
					  
					 

					 
					  if indicator.graph == "spider_line"
					  	f.chart({defaultSeriesType: indicator.graph.split('_').map(&:to_s).last, polar: 'true' })
					  	f.title(text: indicator.name)
					  	f.legend(align: 'center', verticalAlign: 'bottom', y: 0, x: 0, layout: 'horizontal')
					  else
					  	f.chart({defaultSeriesType: indicator.graph.split('_').map(&:to_s).last})
					  	f.title(text: indicator.name)
					  	f.xAxis(categories: x)
					    f.legend(align: 'center', verticalAlign: 'bottom', y: 0, x: 0, layout: 'horizontal')
					  end
			end
			
			@charts.push(instance_variable_set(:"@#{('a'..'z').to_a.shuffle.join}", @chart))
		end
		
		@documentations = Documentation.all
	end

	def sort 
	    params[:indicator].each_with_index do |id, index|
	        Indicator.where(id: id).update_all(position: index + 1)
	    end 

	    head :ok
	end 

	def new
		@indicator = current_user.indicators.build
	end

	def create
		@indicator = current_user.indicators.build(indicator_params)
		if @indicator.save
			redirect_to root_path
		else
			redirect_to root_path
		end
	end


	def show
		@indicator = Indicator.find(params[:id])

	end

	def edit
		@indicator = Indicator.find(params[:id])
		respond_to do |format|
		    format.html  #If it's a html request this line tell rails to look for new_release.html.erb in your views directory
		    format.js #If it's a js request this line tell rails to look for new_release.js.erb in your views directory
		  end
		
	end

	def update
		@indicator = Indicator.find(params[:id])

		if @indicator.update(params[:indicator].permit(:name, :data, :graph, :yaxis,:public, :department_id, :tag_list))
			redirect_to root_path
		else
			redirect_to root_path
		end
	end
	

	def destroy
		@indicator = Indicator.find(params[:id])
		@indicator.destroy
		redirect_to root_path
	end

	def must_be_admin
	    unless current_user && current_user.admin?
	      redirect_to root_path, notice: "must be admin"
	    end
  	end

	private
		def indicator_params
			params.require(:indicator).permit(:name, :data, :graph, :yaxis, :public, :department_id, :tag_list)
		end
end

app/helpers/indicators_helper.rb
module IndicatorsHelper
end

app/views/indicators/_form.html.erb
				<%= form_for @indicator do |f| %>
							<% if @indicator.errors.any? %>
								<div id="errors">
									<h2><%= pluralize(@indicator.errors.count, "error") %> prevented this indicator from saving</h2>
									<ul> 
										<% @indicator.errors.full_messages.each do |msg| %>
											<li><%= msg %></li>
										<% end %>
									</ul>
								</div>
							<% end %>


				<div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title" id="myModalLabel"> Indicator</h4>
                </div>

                <div class="modal-body">
                
							<p>	
                    		 <%= f.check_box :public, data: {toggle: 'toggle', size: 'small', on:'Public', off:'Private', onstyle:"primary", offstyle:"danger"} %>
                    		</p>
                    		<p>
								<%= f.label :department %>
								<%= f.collection_select :department_id, Department.all, :id, :name, {prompt: "Choose a department"}, { :class => 'form-control' } %>
							</p>
							<p>
								<%= f.label :tag_list %><br>
								<%= f.text_field :tag_list,value: @indicator.tag_list.join(","), placeholder: "Tags seperated by commas", :class=>"form-control" %>
							</p>
							<p>
								<%= f.label :graph %><br>
								<%= f.select(:graph, ['column','bar','line','area','stacked_column','stacked_bar','stacked_area', 'spider_line'], {}, { :class => 'form-control' }) %>
							</p>
							<p>
								<%= f.label :name %><br>
								<%= f.text_field :name,:placeholder => "Entrer un titre pour le graphiaue", :class=>"form-control" %>
							</p>
							<p>
								<%= f.label :yaxis %><br>
								<%= f.text_area :yaxis, :placeholder => "Entrer le titre de l'axe Y", :class=>"form-control", :style=>"min-height: 100px;" %>
							</p>
							<p>
								<%= f.label :data %><br>
								<%= f.text_area :data, :placeholder => "Entrer les données", :class=>"form-control", :style=>"min-height: 100px;" %>
							</p>     
							
			                <div class="modal-footer">
			                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
			                   <%= f.submit :class=>"btn btn-primary"  %>
			                </div>
					<% end %>
				</div>


<link href="https://gitcdn.github.io/bootstrap-toggle/2.2.2/css/bootstrap-toggle.min.css" rel="stylesheet">
<script src="https://gitcdn.github.io/bootstrap-toggle/2.2.2/js/bootstrap-toggle.min.js"></script>

app/views/indicators/edit.html.erb
<section class="main-content-wrapper">
    <section id="main-content">
        <div class="row">
        	<div class="col-md-6">
	            <div class="panel panel-default">
	                <div class="panel-heading">
	                	<h3>Edit Indicators</h1>
	                </div>
	                <div class="dashboard-tile detail tile">
	                	
							<%= render 'indicators/form' %>
	                	
	                </div>
	            </div>		
	        </div>                              
        </div>
							
    </section>
</section>


							                 

app/views/indicators/edit.js.erb
$("#modal-window").find(".modal-content").html("<%= j (render 'indicators/form') %>");
$("#modal-window").modal('show');

app/views/indicators/index.html.erb
<section class="main-content-wrapper">
	<section id="main-content">
		 <div class="row">
		 	<div class="col-md-10">
		 		<span style="color: #9eafba;text-decoration: none;font-size: 1.2em;"><i class="fa fa-sitemap fa-1x"> Department:</i></span>
		 		<%= link_to "All", indicators_path, :class => "btn btn-primary btn-xs" %>
			 	<% Department.all.each do |department| %>
			 		<%= link_to department.name, indicators_path(department: department.name), :class => "btn btn-primary btn-xs" %>
			 	<% end %>
			 	<br>	<br>
		 	</div>
		 	<div class="col-md-2">
		 		<div class="pull-right">
			 		
				 		<%= link_to new_indicator_path, {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#modal-window'}  do %><i class="fa fa-bar-chart"></i> Add indicator<% end %>  |  
					 	<%= link_to new_kpi_path, {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#modal-kpi'}  do %><i class="fa fa-dashboard"></i> Add kpi<% end %>
				 	<br>	<br>
				
				</div>
		 	</div>
		 </div>
		 <div class="row">
		 	<div class="col-md-10">
				<span style="color: #9eafba;text-decoration: none;font-size: 1.2em;"><i class="fa fa-tag fa-1x"> tags :</i></span>
				<%= link_to "All", indicators_path, :class => "btn btn-primary btn-xs" %>
			 	<% if Indicator.tag_counts.length > 0 %>
                <% tag_cloud @indicators.tag_counts, %w(css1 css2 css3 css4) do |tag| %>
                    <span class="btn btn-primary btn-xs"><%= link_to tag.name, indicators_path(tag: tag.name), :style=>'color:#FFFFFF;'  %></span>
                <% end %>
              <% else -%>
                <%= content_tag :p, 'No tags' %>
              <% end %>
			 </div>
			 <br>	<br>
		  </div>

								    <div class="row">
										<% @kpis.each.with_index do |kpi, index| %>
											<div class="col-md-3 col-sm-6">
												<div class="dashboard-tile detail tile-<%= kpi.color %>">
													<div class="pull-right">
														<p style="font-size:0.7em;"><%= kpi.updated_at.strftime('%v') %></p>
													</div>
													<div class="pull-left">
													<% if current_user.admin?  %>
															<div class="btn-group">
															    <button type="button" class="btn btn-default btn-xs btn-trans dropdown-toggle" data-toggle="dropdown">
															          <i class="fa fa-cog"></i><span class="caret"></span>
															    </button>
															     <ul class="dropdown-menu" role="menu">
															        <li><%= link_to edit_kpi_path(kpi), {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#modal-kpi'} do %><i class="fa fa-edit"></i> Edit<% end %>
															        </li>
															        <li><%= link_to kpi_path(kpi),data: {:confirm => 'Are you sure?'}, :method => :delete, :class => "button" do %><i class="fa fa-trash-o"></i> Delete<% end %>
															       	</li>
															      </ul>
															</div>
														<% end %>
													</div>
													<div class="content">
														
														<h1 class="text-left timer" data-speed="2500" data-to="180" data-from="0">
															<%= kpi.datum %>
														</h1>
															<p><%= kpi.name %></p>
													</div>
													<div class="icon">
														<i class="fa fa-warning"></i>
													</div>
													
												</div>

											</div>
										<% end %>
									</div>
           							
									
										<div class="row" style='margin-bottom:20px' id="indicators" data-update-url="<%= sort_indicators_url %>">
											<% @index=0 %>
											<% @indicators.each.with_index do |indicator, index| %>
												<% if index.odd? %>
									                    <div class="col-md-6" id="indicator_<%= indicator.id %>">
									       
									                        <div class="panel panel-default">
									                            <div class="panel-heading">
									                                <h5 class="panel-title"><% if current_user.admin? || indicator.user==current_user %><i class="fa fa-arrows-alt handle" ></i> <% end %><%= link_to indicator.department.name, indicators_path(department: indicator.department.name), :class => "btn btn-default btn-xs" %> <%= raw indicator.tag_list.map{|t| link_to t, indicators_path(tag: t), :class =>"btn btn-default btn-xs"}.join(' ')%> <% if indicator.public==true %><button type="button" class="btn btn-primary btn-xs">Public</button> <% else %><button type="button" class="btn btn-danger btn-xs">Private</button><% end %></h5>
									                                <div class="actions pull-right">
									                                	<% if indicator.user==current_user %>
									                                	<div class="btn-group">
										                                       <button type="button" class="btn btn-default btn-xs btn-trans dropdown-toggle" data-toggle="dropdown">
										                                        <i class="fa fa-cog"></i><span class="caret"></span>
										                                      </button>
	
										                                      <ul class="dropdown-menu" role="menu">
										                                        <li><%= link_to edit_indicator_path(indicator), {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#modal-window'}  do %><i class="fa fa-edit"></i> Edit<% end %></li>
										                                        <li><%= link_to indicator_path(indicator),data: {:confirm => 'Are you sure?'}, :method => :delete, :class => "button" do %><i class="fa fa-trash-o"></i> Delete<% end %></li>
										                                      </ul>
										                                    </div>
									                                    <% end %>
									                                </div>
									                            </div>
									                            <div class="panel-body">
																	<div id="graph" style="min-width: 100%; height: 100%; margin: 0 auto">
																		<h2 class="title"></h2>
																			<%= high_chart(('a'..'z').to_a.shuffle.join, @charts[@index]) %>
																			<% @index += 1 %>
																	</div>
														
																	<div class="pull-right">
																		<p style="font-size:0.7em;">Updated at: <%= indicator.updated_at.strftime('%v') %></p>
																	</div>
																</div>
								                            </div>
								                        </div>
								                   
								                <% else %>
								                	
									                   <div class="col-md-6" id="indicator_<%= indicator.id %>">
									                   	  
									                        <div class="panel panel-default">
									                            <div class="panel-heading">
									                                <h5 class="panel-title"><% if current_user.admin? || indicator.user==current_user %><i class="fa fa-arrows-alt handle" style="cursor: move"></i> <% end %><%= link_to indicator.department.name, indicators_path(department: indicator.department.name), :class => "btn btn-default btn-xs" %> <%= raw indicator.tag_list.map{|t| link_to t, indicators_path(tag: t), :class =>"btn btn-default btn-xs"}.join(' ')%>  <% if indicator.public==true %><button type="button" class="btn btn-primary btn-xs">Public</button> <% else %><button type="button" class="btn btn-danger btn-xs">Private</button><% end %></h5>
									                                <div class="actions pull-right">
									                                	<% if indicator.user==current_user %>
									                                	<div class="btn-group">
										                                       <button type="button" class="btn btn-default btn-trans btn-xs dropdown-toggle" data-toggle="dropdown">
										                                        <i class="fa fa-cog"></i><span class="caret"></span>
										                                      </button>
										                                      <ul class="dropdown-menu" role="menu">
										                                        <li><%= link_to edit_indicator_path(indicator), {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#modal-window'}  do %><i class="fa fa-edit"></i> Edit<% end %></li>
										                                        <li><%= link_to indicator_path(indicator),data: {:confirm => 'Are you sure?'}, :method => :delete, :class => "button" do %><i class="fa fa-trash-o"></i> Delete<% end %></li>
										                                      </ul>
										                                    </div>
									                                    <% end %>
									                                </div>
									                            </div>
									                            <div class="panel-body">
																	<div id="graph" style="min-width: 100%; height: 100%; margin: 0 auto">
																		<h2 class="title"></h2>
																			<%= high_chart(('a'..'z').to_a.shuffle.join, @charts[@index]) %>
																			<% @index += 1 %>
																	</div>
																
																	<div class="pull-right">
																		<p style="font-size:0.7em;">Updated at: <%= indicator.updated_at.strftime('%v') %></p>
																	</div>
																</div>
								                            </div>
								                        </div>
								                <% end %>
											<% end %>
										</div>
								
            </section>
         </section>
         <!--main content end-->
         <!-- Basic Modal -->
    <div id="modal-window" class="modal fade" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
		  <div class="modal-dialog" role="document">
		    <div class="modal-content">

		    </div>
		  </div>
	</div>
	<div id="modal-kpi" class="modal fade" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
		  <div class="modal-dialog" role="document">
		    <div class="modal-content">

		    </div>
		  </div>
	</div>
    <!-- End Basic Modal -->
	  <!-- Form Modal -->

	    <!-- End Form Modal -->

app/views/indicators/new.html.erb
<section class="main-content-wrapper">
    <section id="main-content">
        <div class="row">
        	<div class="col-md-6">
	            <div class="panel panel-default">
	                <div class="panel-heading">
	                	<h3>New Indicator</h3>
	                </div>
	               	<div class="dashboard-tile detail tile">
	                	
							<%= render 'form' %>
	                	
	                </div>
	            </div>		
	        </div>                              
        </div>
    </section>
</section>

app/views/indicators/new.js.erb
$("#modal-window").find(".modal-content").html("<%= j (render 'indicators/form') %>");
$("#modal-window").modal('show');

app/views/indicators/show.html.erb
<h1 class="title">
	<%= @indicator.name %>
</h1>

<h1 class="title">
	<%= @indicator.data %>
</h1>

	<%= link_to 'Edit', edit_indicator_path(@indicator) %>
	<%= link_to 'Delete', indicator_path(@indicator), method: :delete, data: {confirm: 'Are you sure?'} %>