config/routes.rb
Rails.application.routes.draw do
  get 'todo_lists/:todo_list_id/tags/:tag', to: 'todo_lists#show', as: :tag
  get 'todo_lists/:todo_list_id/typeahead/:query' => 'todo_items#typeahead'
  resources :todo_lists do
  	resources :todo_items do
        member do
          patch :complete,:incomplete,:efficiency
        end
    end
  end
  resources :indicators do
    collection { post :sort }
  end 
  resources :documentations
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :kpis
  devise_for :users
  root "indicators#index"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Intranet</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

</head>
<% if user_signed_in? %>
<body class="off-canvas">
    <div id="container">
        <header id="header">
            <!--logo start-->
            <div class="brand">
            	 <%= link_to root_path, :class => "logo" do %>Dashboard<% end %>
            </div>
            <!--logo end-->
            <div class="toggle-navigation toggle-left">
                <button type="button" class="btn btn-default" id="toggle-left" data-toggle="tooltip" data-placement="right" title="Toggle Navigation">
                    <i class="fa fa-bars"></i>
                </button>
            </div>
            <div class="user-nav">
                <ul>
                   <li class="dropdown settings">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                    <%= current_user.email %> <i class="fa fa-angle-down"></i>
                    </a>
                        <ul class="dropdown-menu animated fadeInDown">
                           <% if current_user.admin? %>
                                <li>
                                    <%= link_to rails_admin_path do %><i class="fa fa-home"></i> Admin<% end %>
                                </li>
                               <!-- <li>
                                    <%= link_to new_indicator_path, {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#modal-window'}  do %><i class="fa fa-bar-chart"></i> Add indicator<% end %>
                                </li>
                                <li>
                                    <%= link_to new_kpi_path, {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#modal-kpi'}  do %><i class="fa fa-dashboard"></i> Add kpi<% end %>
                                </li>-->
                            <% end %>
                           <!-- <li>
                                <%= link_to edit_user_registration_path  do %><i class="fa fa-edit"></i> Edit<% end %>
                            </li>-->
                            <li>
                                <%= link_to destroy_user_session_path, :method => :delete  do %><i class="fa fa-sign-out"></i> Logout<% end %>
                            </li>
                        </ul>
                    </li>
                </ul>
            </div>
        </header>
        <!--sidebar left start-->
        <nav class="sidebar sidebar-left">
            <h5 class="sidebar-header">Navigation</h5>
            <ul class="nav nav-pills nav-stacked">
               <li class="<%= current_controller?('indicators') ? 'active' : '' %>">
                    <%= link_to root_path do %><i class="fa fa-bar-chart"></i> Indicators<% end %>
                </li>
                <li class="<%= current_controller?('todo_lists') ? 'active' : '' %>">
                    <%= link_to todo_lists_path do %><i class="fa fa-tasks"></i> Task management<% end %>
                </li>
            </ul>
        </nav>
        <!--sidebar left end-->
        <%
=begin 
%>
        <% flash.each do |name, msg| %>
         <div class="flash text-center">
            <%= content_tag(:div, msg, class: "alert alert-success") %>
          </div>
        <% end %>
        <%
=end
%>

<% end %>
		<%= yield %>
    
</body>
</html>